spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: demo2228
    url: jdbc:mysql://localhost:3306/Project_2
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true
server:
  port: 2228
